test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.1fd11805251707b295840f1c62def7efa2becc70.name = "Upgrade from 4.0.4"
