#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/modules/" --source_id="csvimport"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding a configuration file..."

ynh_config_add --template="database.ini.default" --destination="$install_dir/config/database.ini"

chmod 400 "$install_dir/config/database.ini"
chown $app "$install_dir/config/database.ini"

#=================================================
# TWEAK IMAGICK CONFIGURATION TO ALLOW PDF THUMBNAILS GENERATION 
#=================================================
ynh_script_progression "Tweaking ImageMagick conf to allow generation of thumbnails PDF"

sed -i 's/^\s*<policy.*PDF.*/<!--\0-->/g' /etc/ImageMagick-*/policy.xml

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
