#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=256M
ynh_app_setting_set --key=php_memory_limit --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/modules/" --source_id="csvimport"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="database.ini.default" --destination="$install_dir/config/database.ini"
ynh_config_add --template="local.config.php" --destination="$install_dir/config/local.config.php"

#=================================================
# TWEAK IMAGICK CONFIGURATION TO ALLOW PDF THUMBNAILS GENERATION
#=================================================
ynh_script_progression "Tweaking ImageMagick conf to allow generation of thumbnails PDF"

sed -i 's/^\s*<policy.*PDF.*/<!--\0-->/g' /etc/ImageMagick-*/policy.xml

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
