#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=256M

ynh_app_setting_set_default --key=php_memory_limit --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep="config/local.config.php config/database.ini modules themes files"
ynh_setup_source --dest_dir="$install_dir/modules/" --source_id="csvimport"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="database.ini.default" --destination="$install_dir/config/database.ini"
ynh_add_config --template="local.config.php" --destination="$install_dir/config/local.config.php"

chmod 400 "$install_dir/config/database.ini"
chown $app "$install_dir/config/database.ini"
chmod 400 "$install_dir/config/local.config.php"
chown $app "$install_dir/config/local.config.php"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# TWEAK IMAGICK CONFIGURATION TO ALLOW PDF THUMBNAILS GENERATION
#=================================================
ynh_script_progression "Tweaking ImageMagick conf to allow generation of thumbnails PDF"

sed -i 's/^\s*<policy.*PDF.*/<!--\0-->/g' /etc/ImageMagick-*/policy.xml

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
