#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir" --keep="config/local.config.php config/database.ini modules themes files"
ynh_setup_source --dest_dir="$install_dir/modules/" --source_id="csvimport"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="database.ini.default" --destination="$install_dir/config/database.ini"
ynh_add_config --template="local.config.php" --destination="$install_dir/config/local.config.php"

chmod 400 "$install_dir/config/database.ini"
chown $app "$install_dir/config/database.ini"
chmod 400 "$install_dir/config/local.config.php"
chown $app "$install_dir/config/local.config.php"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

ynh_add_fpm_config

ynh_add_nginx_config

#=================================================
# TWEAK IMAGICK CONFIGURATION TO ALLOW PDF THUMBNAILS GENERATION 
#=================================================
ynh_script_progression --message="Tweaking ImageMagick conf to allow generation of thumbnails PDF" --weight=1

sed -i 's/^\s*<policy.*PDF.*/<!--\0-->/g' /etc/ImageMagick-*/policy.xml

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
